version: 2.1

orbs:
  node: circleci/node@1.1.6

jobs:
  build-and-deploy:
    executor:
      name: node/default
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: git config --global user.name "yuukimiyo"
            - run: git config --global user.email "yuuki.miyo@gmail.com"
            - run: yarn
            - run: yarn global add gatsby
            - run: yarn test
            - run: yarn deploy

workflows:
  build-and-deploy:
    jobs:
      - build-and-deploy:
          filters:
            branches:
              only:
                - master
