version: 2.1

orbs:
  node: circleci/node@1.1.6

jobs:
  build:
    docker:
      - image: circleci/node@1.1.6
    steps:
      - checkout
      - run: git config --global user.name "yuukimiyo"
      - run: git config --global user.email "yuuki.miyo@gmail.com"
      - run: yarn
      - run: yarn global add gatsby
      - run: yarn test
      - run: yarn deploy

workflows:
  build:
    jobs:
      - build:
          context: bookshelf.ymiyo.com
          filters:
            branches:
              only:
                - master
